# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mbbot}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wolfram R. Sieber", "David Sifry (contributor)"]
  s.date = %q{2009-08-31}
  s.description = %q{easy to use framework to build services, chatbots, gateways atop Twitter/StatusNet}
  s.email = %q{Wolfram.R.Sieber@GMail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "License",
     "README",
     "Rakefile",
     "Token.rb",
     "VERSION",
     "about.txt",
     "changelog",
     "config/credentials/twitterbot.yaml",
     "config/latest_tweeds.yaml",
     "doc/uB_bot_framework.dot",
     "doc/uB_bot_framework.png",
     "micro_blog_bot.rb",
     "micro_blog_bot_runner.rb",
     "micro_blog_connector.rb",
     "micro_blog_consts.rb",
     "micro_blog_friending.rb",
     "micro_blog_messaging_io.rb",
     "micro_blog_shadow.rb",
     "patches/gems/twitter-0.4.1/lib/twitter/base.wrs.diff",
     "patches/gems/twitter-0.6.12/lib/twitter/add_public_timeline_method.patch",
     "sample_chatbot.rb",
     "sample_messade_IDs.txt",
     "test/fixtures/identica-enabled.yaml",
     "test/fixtures/original-twitterbot.yaml",
     "test/fixtures/other-enabled_with_invalid_api_URI.yaml",
     "test/fixtures/other-enabled_with_missing_api.yaml",
     "test/fixtures/twitter-enabled.yaml",
     "test/tc_micro_blog_connector.rb",
     "test/tc_micro_blog_friending.rb",
     "test/tc_micro_blog_messaging_io.rb",
     "test/ts_twitter_bot.rb"
  ]
  s.homepage = %q{http://github.com/dagobart/mbbot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{eases to build services for micro-blogging services such as Twitter and StatusNet}
  s.test_files = [
    "test/tc_micro_blog_friending.rb",
     "test/tc_micro_blog_messaging_io.rb",
     "test/tc_micro_blog_connector.rb",
     "test/ts_twitter_bot.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, ["= 0.4.1"])
    else
      s.add_dependency(%q<twitter>, ["= 0.4.1"])
    end
  else
    s.add_dependency(%q<twitter>, ["= 0.4.1"])
  end
end
